### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by MissBehavin** [uetopia/ProMMO#1]
https://github.com/uetopia/UnrealEngine/tree/4.19.0_UETOPIA_OSS_Enhancements is invalid or removed.

**Comment by edcolmar** [comment]
In order to see the engine source code in github you need to go through Epic's approval process, detailed here:  https://www.unrealengine.com/en-US/ue4-on-github

**Comment by uetopia** [comment]
In order to see the engine source code in github you need to go through Epic's approval process, detailed here: https://www.unrealengine.com/en-US/ue4-on-github
