### ISSUE TITLE
Link is broken for patched engine

### ISSUE THREAD

**Issue by grimsikk** [uetopia/ProMMO#2]
https://github.com/uetopia/UnrealEngine/tree/4.22.2_UETOPIA

The above link leads me to a 404 error page.

I really would like to use this system to start my rpg project; it looks like a fantastic set of tools. I hope to hear back from you on this soon! Stay safe out there :)

**Comment by uetopia** [comment]
Hello Grimsikk 

You need to follow [Epic's github authorization steps](https://www.unrealengine.com/en-US/ue4-on-github) in order to unlock the engine source.

**Comment by grimsikk** [comment]
I am connected though, and Epic Games is authorized. It still leads to the 404 error page.

**Comment by grimsikk** [comment]
It seems to work now, thank you.
